### ISSUE TITLE
Crashes on login for some people

### ISSUE THREAD

**Issue by BlueDrink9** [noisive/stoned-crone#13]

**Comment by BlueDrink9** [comment]
May eventually require parser to try multiple methods before it works.

**Comment by will-shaw** [comment]
Could be the parser... seems evision change the tool tip slightly, hopefully fixed in #5

**Comment by BlueDrink9** [comment]
Sweet!

**Comment by BlueDrink9** [comment]
But mine works though... Does yours work on the old version too?

**Comment by will-shaw** [comment]
Not sure, will have to look into it.

**Comment by BlueDrink9** [comment]
Same as #19
