### ISSUE TITLE
Crashes when no data is loaded on right swipe

### ISSUE THREAD

**Issue by BlueDrink9** [noisive/stoned-crone#3]

**Comment by will-shaw** [comment]
Also possible crash when swiping left past week start.

**Comment by will-shaw** [comment]
This is fixed for now, I've just added a check to make sure we don't pass day 7. When we add extra weeks this can be removed/updated to the day of the last event.

**Comment by BlueDrink9** [comment]
Shot, ty. May need extra testing, eli put a di#f check in before that didn't always work
