### ISSUE TITLE
Red text on login screen  (one moment)

### ISSUE THREAD

**Issue by will-shaw** [noisive/stoned-crone#32]

**Comment by BlueDrink9** [comment]
... mind explaining what this means?

**Comment by BlueDrink9** [comment]
@will-shaw what was this "bug"? Was this the changing of the feedback text on the login screen to red, to represent feedback rather than the default colour associated with buttons?

**Comment by will-shaw** [comment]
Kind of. Perhaps something to do with Xcode 9 which seemed to have removed the preset color which was set on the label, which was now showing up red.
Essentially while displaying "One moment" and "Enter your eVision details" the label was red, and wasn't updated to blue (now black) until the "Logging you in" message.
While fixing this I switched the information color to black so it doesn't look like a "button" in Apple world.

**Comment by BlueDrink9** [comment]
Ok. Not at all a bug, I had specifically changed it to red to make it look like feedback. I guess black works too, red just looks like errors. But errors are red anyway, right?

**Comment by will-shaw** [comment]
Yeh I'd say errors are red. Plus the label was only red until it is set to blue in the code, just as it says "Logging you in". I've changed it so that the info is only black with informative cues, and only red with a login error of some kind.

**Comment by BlueDrink9** [comment]
haha oh, oops. My bad. Thanks!
